name: Buf Lint

on: 
  pull_request: # Apply to all pull requests

jobs:
  lint-protos:
    runs-on: ubuntu-latest
    steps:
      # Run `git checkout`
      - uses: actions/checkout@v4

      # Install the `buf` CLI
      - uses: bufbuild/buf-setup-action@v1

      # Lint your Protobuf sources
      - uses: bufbuild/buf-lint-action@v1
        with:
          input: .
          config: buf.work.yaml
